networks:
  web:
    external: true

services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    networks:
      - ${DOCKER_NETWORK}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - 'OLLAMA_BASE_URL=http://ollama.h0st.fun:11434'
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng:8080?q=<query>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./open-webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`ollama.${APP_DOMAIN}`)"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls=true"
      - "traefik.http.routers.open-webui.tls.certresolver=myresolver"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    extra_hosts:
      - host.docker.internal:host-gateway

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
          - 8081:8080
    networks:
      - ${DOCKER_NETWORK}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./searxng:/etc/searxng
    depends_on:
      - open-webui
    restart: unless-stopped
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.open-webui.rule=Host(`search.${APP_DOMAIN}`)"
          - "traefik.http.routers.open-webui.entrypoints=websecure"
          - "traefik.http.routers.open-webui.tls=true"
          - "traefik.http.routers.open-webui.tls.certresolver=myresolver"
          - "traefik.http.services.open-webui.loadbalancer.server.port=8081"

#   stable-diffusion-download:
#     build: ./stable-diffusion-webui-docker/services/download/
#     image: comfy-download
#     environment:
#       - PUID=${PUID:-1000}
#       - PGID=${PGID:-1000}
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./stable-diffusion-webui-docker/data:/data
#
#   stable-diffusion-webui:
#     build: ./stable-diffusion-webui-docker/services/comfy/
#     image: comfy-ui
#     environment:
#       - PUID=${PUID:-1000}
#       - PGID=${PGID:-1000}
#       - CLI_ARGS=
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - ./stable-diffusion-webui-docker/data:/data
#       - ./stable-diffusion-webui-docker/output:/output
#
#     stop_signal: SIGKILL
#     tty: true
#     deploy:
#       resources:
#         reservations:
#           devices:
#               - driver: nvidia
#                 device_ids: ['0']
#                 capabilities: [compute, utility]
#     restart: unless-stopped
#     networks:
#       - ${DOCKER_NETWORK}
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.stable-diffusion.rule=Host(`sd.${APP_DOMAIN}`)"
#       - "traefik.http.routers.stable-diffusion.entrypoints=https"
#       - "traefik.http.routers.stable-diffusion.tls=true"
#       - "traefik.http.routers.stable-diffusion.tls.certresolver=cloudflare"
#       - "traefik.http.services.stable-diffusion.loadbalancer.server.port=7860"

# whisper
  mongo:
    image: mongo
    env_file:
      - .env
    networks:
      - ${DOCKER_NETWORK}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./whisper/db_data:/data/db
      - ./whisper/db_data/logs/:/var/log/mongodb/
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-whishper}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-whishper}
    command: ['--logpath', '/var/log/mongodb/mongod.log']

  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    env_file:
      - .env
    networks:
      - ${DOCKER_NETWORK}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./whisper/libretranslate/data:/home/libretranslate/.local/share
      - ./whisper/libretranslate/cache:/home/libretranslate/.local/cache
    user: root
    tty: true
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - LT_DISABLE_WEB_UI=True
      - LT_LOAD_ONLY=${LT_LOAD_ONLY:-en,fr,es}
      - LT_UPDATE_MODELS=True

  whisper:
    container_name: whisper
    pull_policy: always
    image: pluja/whishper:latest
    env_file:
      - .env
    networks:
      - ${DOCKER_NETWORK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./whisper/uploads:/app/uploads
      - ./whisper/logs:/var/log/whishper
      - ./whisper/models:/app/models
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`whisper.${APP_DOMAIN}`)"
      - "traefik.http.routers.whisper.entrypoints=https"
      - "traefik.http.routers.whisper.tls=true"
      - "traefik.http.routers.whisper.tls.certresolver=cloudflare"
      - "traefik.http.services.whisper.loadbalancer.server.port=80"
    depends_on:
      - mongo
      - translate
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PUBLIC_INTERNAL_API_HOST=${WHISHPER_HOST}
      - PUBLIC_TRANSLATION_API_HOST=${WHISHPER_HOST}
      - PUBLIC_API_HOST=${WHISHPER_HOST:-}
      - PUBLIC_WHISHPER_PROFILE=gpu
      - WHISPER_MODELS_DIR=/app/models
      - UPLOAD_DIR=/app/uploads