---
- name: Setup Docker and NVIDIA Container Toolkit on a Ubuntu machine
  hosts: ubuntu_hosts
  become: yes
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisite packages for NVIDIA drivers
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - ubuntu-drivers-common
        - curl
        - gpg

    - name: Reboot the machine
      reboot:
        msg: "Reboot initiated by Ansible for NVIDIA runtime configuration"
        reboot_timeout: 600

    - name: Wait for the machine to come back online
      wait_for_connection:
        timeout: 60




    - name: Install NVIDIA driver recommended version
      command: sudo ubuntu-drivers install
      args:
        creates: /usr/bin/nvidia-smi

    - name: Install specific NVIDIA utilities
      ansible.builtin.package:
        name: nvidia-utils-{{ ansible_facts['nvidia-utils-version'] }}
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker APT repository
      copy:
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb-release'] }} stable
        dest: /etc/apt/sources.list.d/docker.list
        force: yes


    - name: Add NVIDIA GPG key
      shell: curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add NVIDIA Container Toolkit repository
      shell: curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
        state: present

    - name: Install NVIDIA Container Toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        state: present

    - name: Debug ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Configure NVIDIA runtime
      command: sudo nvidia-ctk runtime configure --runtime=docker
      register: configure_nvidia_runtime
      failed_when: configure_nvidia_runtime.rc != 0
      ignore_errors: no

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Test NVIDIA container toolkit
      shell: sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
      register: result
      failed_when: "'NVIDIA-SMI' not in result.stdout"

    - name: Print test result
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
